export const cartConstants = {

  CART_ADD_REQUEST: 'CART_REQUEST',
  CART_ADD_SUCCESS: 'CART_ADD_SUCCESS',
  CART_ADD_INIT: 'CART_ADD_INIT',
  CART_ADD_FAILURE: 'CART_ADD_FAILURE', 
  CART_REMOVE_SUCCESS: 'CART_REMOVE_SUCCESS',
  CART_EMPTY_SUCCESS:'CART_EMPTY_SUCCESS',

  AMOUNT_ADD_FAILURE: 'AMOUNT_ADD_FAILURE', 
  AMOUNT_ADD_SUCCESS: 'CART_REMOVE_SUCCESS',

  PACKGE_DETAILS_REQUEST:'PACKGE_DETAILS_REQUEST', 
  PACKGE_DETAILS_SUCCESS: 'PACKGE_DETAILS_SUCCESS',
  PACKGE_DETAILS_FAILED: 'PACKGE_DETAILS_FAILED',

  PACKGE_UPDATE_REQUEST:'PACKGE_UPDATE_REQUEST', 
  PACKGE_UPDATE_SUCCESS: 'PACKGE_UPDATE_SUCCESS',
  PACKGE_UPDATE_FAILED: 'PACKGE_UPDATE_FAILED',

  PACKGE_LIST_REQUEST:'PACKGE_LIST_REQUEST', 
  PACKGE_LIST_SUCCESS: 'PACKGE_LIST_SUCCESS',
  PACKGE_LIST_FAILED: 'PACKGE_LISTL_FAILED',

  LABEL_REQUEST:'LABEL_REQUEST', 
  LABEL_SUCCESS: 'LABEL_SUCCESS',
  LABEL_FAILED: 'LABEL_FAILED',

  SUBCAT_REQUEST:'SUBCAT_REQUEST', 
  SUBCAT_SUCCESS: 'SUBCAT_SUCCESS',
  SUBCAT_FAILED: 'SUBCAT_FAILED',

  CAT_REQUEST:'CAT_REQUEST', 
  CAT_SUCCESS: 'CAT_SUCCESS',
  CAT_FAILED: 'CAT_FAILED',
  CAT_UPDATE: 'CAT_UPDATE',

  SHOW_ADDRESS_SUCCESS:'SHOW_ADDRESS_SUCCESS',
  SHOW_ADDRESS_FAILURE:'SHOW_ADDRESS_FAILURE',
  SHOW_ADDRESS_REQUEST:'SHOW_ADDRESS_REQUEST',

  PROFILE_REQUEST:'PROFILE_REQUEST',
  PROFILE_SUCCESS:'PROFILE_SUCCESS',
  PROFILE_FAILURE:'PROFILE_FAILURE',

};

