require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'lootbox' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'AppAuth',  '~> 1.4.0'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'



  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  #pod 'Firebase/Analytics'

  # Add the pod for Firebase Cloud Messaging
  #pod 'Firebase/Messaging', ~6.13.0

  target 'lootboxTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'lootbox-tvOS' do
  # Pods for lootbox-tvOS

  target 'lootbox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end